### ISSUE TITLE
Open Beta - changes - fix http extraction SQLite locking errors

### ISSUE THREAD

**Issue by battle-panda** [appgardenstudios/hyaline#162]
# Description
When running http extraction, we are getting SQLite locking errors: `database is locked (5) (SQLITE_BUSY)`, which is causing the extraction to fail.

## Source(s)
- #19 

## Outcome
As a developer, I can run a hyaline http extract on a medium-large website successfully

## Size
Small

## Justification
Hyaline extract needs to work properly for http documentation sources

# Prioritization
High

# Plan
1. Add a mutex to linearize the writes to SQLite when crawling.

## Estimate
1-2 hours

## Plan Endorsement
2025-07-01 @compiledpanda @battle-panda 

# Implementation
* https://github.com/appgardenstudios/hyaline/pull/172

## Execution Result
* https://github.com/appgardenstudios/hyaline/commit/dc9c9ab0edd6603e9bc7a61068c3937ad7a14d86

## Communication
N/A

## Verification Result
Extraction no longer produces `SQLITE_BUSY` errors. However, now that https://github.com/appgardenstudios/hyaline/pull/173 has landed there are constraint errors when extracting data. 

# Completion
2025-07-02 @compiledpanda 

# Review
2025-07-02 @compiledpanda @battle-panda 

## Evaluation
Straightforward, but we found some other issues when testing that surfaced when the changes for #157. See the discussion in the evaluation there and the notes below

An extract using this configuration produced some additional errors
```yaml
systems:
  - id: test
    documentation:
      - id: http
        type: html
        options:
          selector: ".text-left"
        extractor:
          type: http
          options:
            baseUrl: http://localhost:1313/documentation
          include:
            - "**/*"
```

<img width="1376" alt="Image" src="https://github.com/user-attachments/assets/9db61aea-35dc-48b8-ba26-4a0dcfbe14d6" />

## Validation
I can run a hyaline http extract on a medium-large website successfully (with regards to `SQLITE_BUSY` errors)

## Follow Up
* (none) - Handled in the Follow Up for #157 

# Finished
2025-07-02 @compiledpanda @battle-panda
