### ISSUE TITLE
Open Beta - integrations

### ISSUE THREAD

**Issue by compiledpanda** [appgardenstudios/hyaline#24]
# Definition
Integrations with GitHub Actions.

## Need
As a user, I need the ability to use Hyaline within a GitHub Action workflow. More specifically, I should be able to:
* Run Hyaline to extract the current set of code/documentation (on main or in a PR).
* Run Hyaline to extract the changed set of code/documentation for a PR.
* Run Hyaline to check the PR change and post the results to the PR.
* Run additional Hyaline commands as needed.

## Outcome
After this feature is complete I will be able to use Hyaline within a GitHub Action to extract and check the documentation for a system, have the results posted as a comment on a PR, be able to gate a PR based on the successful run of a Hyaline check, and run arbitrary `hyaline` commands.

## Justification
See #19.

# Prioritization
see #19.

# Design
Create a basic Check PR GitHub Action that bundles everything needed for a basic PR integration into a single step, and then provide an action that sets up Hyaline so that the customer can run Hyaline however they wish.

To help with the Check PR Action we will create a helper function that takes the result of `hyaline check change` and comments on a PR as needed.

The overall plan is to create 2 GitHub actions (install and check PR), and then use those for Hyaline to dogfood Hyaline on Hyaline.

* https://github.com/appgardenstudios/hyaline/issues/101
* https://github.com/appgardenstudios/hyaline/issues/102
* https://github.com/appgardenstudios/hyaline/issues/103

### Hyaline Helper Function
`hyaline update pr` will take the results.json file from a run of `hyaline check change` and create/replace the Hyaline comment on the PR.

A few notes:
* f one or more items in the checklist have been checked, preserve that across updates. Only return a 0 exit code when there are no unchecked items in the list in the comment.
* Allow the pre and post text to the list to be customized
* If the PR updates documentation in the repository, add it to the list and auto-check it. Later on we may want to enhance hyaline to look at the contents of the actual update to see if everything is caught.

**Example Items Found Comment**:
```
The following Documentation appears to be related to this PR, and should be checked and updated if needed:
- [ ] <Document><#<Section>> - <Message>
    <Action if present>
- [ ] <Document><#<Section>>
- [ ] <Document><#<Section>>

Please check the box next to each Documentation item after you have checked and/or updated it. Thanks!
```

**Example No Items Found Comment**:
```
Hyaline did not find any documentation related to the contents of this PR. If you are aware of documentation that should have been updated please update it and let your Hyaline administrator know about this message. Thanks!
``` 

### GitHub Actions
Create the following GitHub Actions that can be used by customers to integrate Hyaline into their CI workflows:
* Check PR
* Setup CLI

After the Setup CLI action is run the customer can use the `hyaline` cli to execute whatever additional commands they need/desire.

**Example Check PR Usage**:
```
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: hyaline
        uses: appgardenstudios/hyaline-actions/check-pr@v1
        with:
          config: './.hyaline-config.yaml'
          system: 'my-system'
          base: ${{ GITHUB_BASE_REF }}
          head: ${{ GITHUB_HEAD_REF }}
          pr: ${{ github.event.number }}
      - name: Check Results
        if: ${{ steps.hyaline.outputs.returnCode }} != '0'
        run: exit 1
```

**Example Setup Usage**:
```
on:
  push:
    branches:
      - main

jobs:
  extract docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appgardenstudios/hyaline-actions/setup@v1
      - name: Extract Current
        run: |
          hyaline extract current --config ./.hyaline-config.yaml --system my-system --output ./current.db
```

## Estimate
See child issues

## Design Endorsement
2025-05-16 @compiledpanda 

# Build

## Estimate Update(s)
(none)

## Verification
See child changes

## Communication
N/A

# Completion
2025-07-03 @compiledpanda 

# Validation
2025-07-03 @compiledpanda @battle-panda 

## Review
- See child changes
- This one ended up being approximately what was specced. There is definitely room for improvement in the ergonomics overall, but this will work as an initial release.

## Confirmation
A user is able to use Hyaline within a GitHub Action to extract and check the documentation for a system, have the results posted as a comment on a PR, be able to gate a PR based on the successful run of a Hyaline check, and is able to run arbitrary hyaline commands.

## Follow Up
- (none)

# Finished
2025-07-03 @compiledpanda @battle-panda
