### ISSUE TITLE
Open Beta - hyaline - extract current

### ISSUE THREAD

**Issue by compiledpanda** [appgardenstudios/hyaline#36]
# Description
Enhance the `hyaline extract current` command.

## Source(s)
* Feature: https://github.com/appgardenstudios/hyaline/issues/23.

## Outcome
After this change is complete customers will be able to use `hyaline extract current` to extract documentation from fs, git, and http source(s).

## Size
Medium.

## Justification
See https://github.com/appgardenstudios/hyaline/issues/23.

# Prioritization
See https://github.com/appgardenstudios/hyaline/issues/23.

# Plan
We will leave the overall behavior of `hyaline extract current` as is as it relates to the purpose and outcome of the command (i.e. extract the current set of code and documentation for a system and put it in an SQLite database). That said, we will be updating both the schema and the config and adding the ability to extract from git (code & docs) and http (docs only) sources.

1. https://github.com/appgardenstudios/hyaline/issues/37 - Update the fs extractor to use the updated schema and configuration to extract code and docs.
2. https://github.com/appgardenstudios/hyaline/issues/38 - Add a git extractor to extract code and docs from a remote git repo (ssh and http(s)).
3. https://github.com/appgardenstudios/hyaline/issues/39 - Add an http extractor to extract docs (no code) from an http(s) server.

### Schema
Based on what we learned from the PoC, several columns were dropped or renamed, and the format of the table and column naming was updated.

#### SYSTEM
* ID - The ID of the system (as defined in the config)

#### CODE
* ID - The ID of the code (as defined in the config)
* SYSTEM_ID - The ID of the system (in the SYSTEM table)
* PATH - The path to the code (as defined in the config)

#### FILE
* ID - The relative path of the file (to the PATH in the CODE table)
* CODE_ID - The ID of the code (in the CODE table)
* SYSTEM_ID - The ID of the system (in the SYSTEM table)
* ACTION - The change action, blank for current
* RAW_DATA - The raw contents of the file

#### DOCUMENTATION
* ID - The ID of the documentation (as defined in the config)
* SYSTEM_ID - The ID of the system (in the SYSTEM table)
* TYPE - The type of documentation (md | html)
* PATH - The path to the documentation (as defined in the config)

#### DOCUMENT
* ID - The relative path of the document (to the PATH in the DOCUMENTATION table)
* DOCUMENTATION_ID - The ID of the documentation (in the DOCUMENTATION table)
* SYSTEM_ID - The ID of the system (in the SYSTEM table)
* TYPE - The type of the raw documentation (md | html)
* ACTION - The change action, blank for current
* RAW_DATA - The raw contents of the document
* EXTRACTED_DATA - The extracted contents of the document in markdown. For markdown documents this will be the same as RAW_DATA (whitespace trimmed), but for html this will be the section of the html containing the documentation that has been parsed (which will cleanup most malformed html) and converted to markdown.

#### SECTION
* ID - The relative path of the document (to the PATH in the DOCUMENTATION table) combined with the section hierarchy
* DOCUMENT_ID - The ID of the document (in the DOCUMENT table)
* DOCUMENTATION_ID - The ID of the documentation (in the DOCUMENTATION table)
* SYSTEM_ID - The ID of the system (in the SYSTEM table)
* NAME - The name of the section (trimmed and with any `#`s removed)
* PARENT_ID - The ID of the parent section, blank if none
* PEER_ORDER - The order of the section among its peers (0 based)
* EXTRACTED_DATA - The extracted contents of the section (extracted from DOCUMENT.EXTRACTED_DATA)

Note: The SECTION.ID is constructed by appending the section's title (including parent titles to the root of the document) to the Document ID separated by `#`. For example, the sub-section `Foo` (parent `Bar`) in README.md would have an ID of `README.md#Bar#Foo`. Note that any `#` symbols in the section titles are stripped, any pre or post whitespace is removed from the section title, but any internal whitespace in the title remains (for example `README.md#My Section#My Subsection` is valid).

### Configuration
We will be moving to an include/exclude pattern and away from presets/globs. This will unify the configuration concepts between code and docs. We will also be creating a extractor specific config property that can be used if that extractor is in use (i.e. git extractor has a git sub-object for git specific config, http extractor has a http sub-object, etc...).

**Example Config**:
```
systems:
  - id: my-system
    code:
      - id: my-fs-app
        extractor: fs
        path: ./
        include:
          - package.json
          - "./**/*.js"
        exclude:
          - "./**/*test.js"
      - id: my-git-app
        extractor: git
        path: git@github.com:appgardenstudios/hyaline.git
        #path: https://github.com/appgardenstudios/hyaline.git
        git:
          ssh-key: ${GITHUB_KEY}
        include:
          - package.json
          - "./**/*.js"
        exclude:
          - "./**/*test.js"
    docs:
      - id: my-fs-docs
        type: md
        extractor: fs
        path: ./
        include:
          - "./**/*.md"
      - id: my-git-docs
        type: md
        extractor: git
        path: git@github.com:appgardenstudios/hyaline.git
        #path: https://github.com/appgardenstudios/hyaline.git
        git:
          ssh-key: ${GITHUB_KEY}
        include:
          - "./**/*.md"
      - id: my-http-docs
        type: html
        extractor: http
        http:
          headers:
            - key: Authorization
              value: ${MY_AUTH_HEADER}
          selector: "main"
        path: https://www.hyaline.dev/docs/
        include:
          - "*"
        exclude:
          - "./**/*.jpg"
```

## Estimate
Based on child changes, 7-12 days

## Plan Endorsement
2025-03-26 @compiledpanda 

# Implementation
See child changes.

## Execution Result
See child changes.

## Communication
See child changes.

## Verification Result
The verification performed for the child changes was re-run to verify all 3 changes still work successfully.

# Completion
2025-04-07 @compiledpanda 

# Review
2025-04-08

## Evaluation
The implementation as it stands now should provide a firm foundation to build on for additional extractors and/or information being extracted. Nothing additional to add past what was called out in the sub-changes.

## Validation
Customers are able to use `hyaline extract current` to extract code and documentation from fs, git, and http source(s).

## Follow Up
(none)

# Finished
2025-04-08 @compiledpanda
