### ISSUE TITLE
Open Beta - hyaline - check change

### ISSUE THREAD

**Issue by compiledpanda** [appgardenstudios/hyaline#43]
# Description
Implement the `hyaline check change` command.

## Source(s)
* Feature: https://github.com/appgardenstudios/hyaline/issues/23.

## Outcome
After this change is complete a developer will be able to run `hyaline check change` and see the results of the check(s) on the system change identified in the command.

## Size
Large.

## Justification
See https://github.com/appgardenstudios/hyaline/issues/23.

# Prioritization
See https://github.com/appgardenstudios/hyaline/issues/23.

# Plan
1. Detect renames in `change.db`
   * Add an additional column to store original name
   * Support `Rename` as an action
2. Stub in `hyaline check change` command
   * `--config <config.yaml>`
   * `--current <current.db>`
   * `--change <change.db>`
   * `--system <systemID>`
   * `--output <output.json>`
   * `--suggest`
3. Implement check change
   * For each code change in `change.db`:
     * Respect `updateIf` and add document to be updated if this change matches one (or more) of the globs in the config
     * Query LLM to see which document(s) should be updated for that change (if any) and a rationale as to why
       * Pass in list of documents and their purpose(s) as part of the context
     * Consider adding tools so the llm can get lists of files/documents and get specific files/documents/sections, etc...
   * Compile the list of documents that should be changed (sort by number of changes referencing the document) and output docs with their rationale
     * Take into account if a document in the list of docs to update is in the change set
4. Implement check change --suggest
   * For each document that should be updated, ask llm what change should be made (passing in changed files that prompted that document from above) and record the suggestion in the output

### Config updates
```yaml
rules:
  - id: basic-repo
    documents:
      - path: README.md
        purpose: The purpose of the document
        required: true # bool, error if not present
        ignore: false # bool, if true do/check nothing
        updateIf: # (anything + specific action in change.db)
          touched: ["glob"]
          added: ["glob"]
          modified: ["glob"]
          deleted: ["glob"]
          renamed: ["glob"]
        sections:
          - id: Section Title
            purpose: The purpose of the section
            required: true
            ignore: false
            updateIf: ...
            sections: ...
systems:
  - id: local
    code: ...
    docs:
      - id: my-app
        type: ...
        rules: ["basic-repo"]
```

### Output
```js
{"recommendations": [{
  "system": "<The system ID>",
  "documentation": "<The ID of the documentation set>",
  "document": "<The path to/ID of the document>",
  "section": "<The path to/ID of the section>", // blank if not a section
  "recommendation": "<Details about the recommended update>",
  "rationale": "<Details about why this update may be needed>",
  "changed": false, // true if document/section was included in the change set
  "suggestion": "<The suggested change>", // only set if --recommend flag set
}]}
```

## Estimate
2-4 days.

## Plan Endorsement
2025-04-24 @compiledpanda 

# Implementation
* https://github.com/appgardenstudios/hyaline/pull/59
* https://github.com/appgardenstudios/hyaline/pull/61
* https://github.com/appgardenstudios/hyaline/pull/62

## Execution Result
* https://github.com/appgardenstudios/hyaline/commit/6f87808df836b9ea47e89e848749919e4ed72ae3
* https://github.com/appgardenstudios/hyaline/commit/75a061615dca1d1e691f5db4b8e9ba6a76dc9214
* https://github.com/appgardenstudios/hyaline/commit/848a8f2dd6dc34ed294b16d9749f8750c70396da

## Communication
N/A

## Verification Result
The command `hyaline check change` works with and without the suggest flag to identify documentation changes needed and (optionally) suggestions. A video of the verification is below.

**Verification Link**: [Change 43 - check change](https://drive.google.com/file/d/1JNImpLc__EemXup2LmLRBibIx_t9rIZw/view?usp=drive_link)

Note: Both unit and e2e tests are present and passing

# Completion
2025-05-06 @compiledpanda 

# Review
2025-05-08 @compiledpanda 

## Evaluation
The implementation went fairly smoothly overall, and the existing implemetation patterns mostly held. A few notes:
* It might be nice to look at the contents of the diff and skip calling the llm if there are only whitespace changes (which may not work with languages like python...). I'm not sure if this is worth baking into the logic itself at this point. We will hold off making changes for now but keep this in mind for a later date.
* It might be good to group up changes by document when determining the suggestion (we calculate a document and document section suggestions separately). There is definitely something here, and when we get to implementing the logic for handling GitHub actions and PR checks we will need to (potentially) address this.
* It might be nice to add document metadata to the section suggestion prompt. This will greatly depend on the handling of documents and sections together, so we will need to see what happens with the note above.

## Validation
A developer is able to run `hyaline check change` and see the results of the check(s) on the system change identified in the command.

## Follow Up
* (None)

# Finished
2025-05-08 @compiledpanda
