### ISSUE TITLE
Open Beta - hyaline - generate config

### ISSUE THREAD

**Issue by compiledpanda** [appgardenstudios/hyaline#45]
# Description
Implement the `hyaline generate config` command.

## Source(s)
* Feature: https://github.com/appgardenstudios/hyaline/issues/23.

## Outcome
After this change is complete a developer will be able to run `hyaline generate config` and the configuration rules for the system will be output to the console.

## Size
Medium.

## Justification
See https://github.com/appgardenstudios/hyaline/issues/23.

# Prioritization
See https://github.com/appgardenstudios/hyaline/issues/23.

# Plan
1. Stub in `hyaline generate config` command
   * `--config <config.yaml>`
   * `--current <current.db>` 
   * `--system <systemID>`
   * `--output <output.yaml>`
   * `--include-purpose`
2. Implement generate
   * Loop through each document for each documentation ID in the config and see if there is a matching rule (note documentation that are in the current db but not in the config (docs) and skip them)
   * If there is a match, loop through the sections and see if there is a matching section
   * If there is not a matching document/section rule:
     * Call the LLM to generate a purpose statement if `--include-purpose` flag is set
       * Update to using the [go sdk for anthropic](https://github.com/anthropics/anthropic-sdk-go) 
     * Add a rule for the document/section
   * When complete, output the rules section(s) for ONLY the rules that were referenced by the docs config for the system.
3. e2e tests
   * Create a basic e2e test w/ and w/o the `--include-purpose` flag
   * [Redirect Anthropic to a local server](https://pkg.go.dev/github.com/anthropics/anthropic-sdk-go/option#WithBaseURL) that responds with a pre-baked response
   * Start the local server similar to how we did when testing http extraction

### Config format
```yaml
rules:
  - id: basic-repo
    documents:
      - path: README.md
        purpose: The purpose of the document
        required: true # bool, error if not present
        ignore: false # bool, if true do/check nothing
        sections:
          - id: Section Title
            purpose: The purpose of the section
            required: true
            ignore: false
            sections: ...
systems:
  - id: local
    code: ...
    docs:
      - id: my-app
        type: ...
        rules: ["basic-repo"] 
```

## Estimate
2-4 days

## Plan Endorsement
2025-04-21 @compiledpanda 

# Implementation
https://github.com/appgardenstudios/hyaline/pull/58

## Execution Result
https://github.com/appgardenstudios/hyaline/commit/170a352bdde1ce68e1a4fd6d327174b830678fd8

## Communication
N/A

## Verification Result
The creation/extension of rules for a system (with and without purpose) was completed and the resulting video is linked below.

**Verification Link**: [Change 45 - generate config](https://drive.google.com/file/d/10TtkozOedAY2_JCBrxrF_de3MJp6S9bB/view?usp=drive_link)

# Completion
2025-04-25 @compiledpanda 

# Review
2025-04-28 @compiledpanda 

## Evaluation
The implementation was fairly straightforward. The Anthropic SDK itself felt a bit over-engineered with the types it uses, but it should be ok. Once thing that came up was that it might be nice to have a corresponding `hyaline update/check config` that takes a look at the existing documents/sections and checks the purpose statement on those to make sure they are correct. It probably isn't necessary since `hyaline generate config` will add missing docs/sections, but it might be a nice to have in the future depending on how people use this feature.

## Validation
a developer is able to run `hyaline generate config` and the configuration rules for the system were output to the output file (instead of the console). This small change in functionality is acceptable.

## Follow Up
(none)

# Finished
2025-04-28 @compiledpanda
