### ISSUE TITLE
PoC - Check (current)

### ISSUE THREAD

**Issue by compiledpanda** [appgardenstudios/hyaline#5]
# Description
Perform a basic check on the extracted documentation.

## Source(s)
* Change: #2

## Outcome
After this change is complete a developer will be able to run `hyaline check` to check and make sure the extracted documentation contains a section on running the system locally. For the sake of this PoC this will be checking that the main README.md file has a section titled `Running Locally` and that section has content.

## Size
Medium

## Justification
See https://github.com/appgardenstudios/hyaline/issues/2

# Prioritization
See https://github.com/appgardenstudios/hyaline/issues/2

# Plan

1. Wire up `hyaline check`
    1. --config - Path to the yaml configuration file
    1. --current - Path to the current data set database
    1. --system - The ID of the system to check
1. Read/Validate configuration
    1. Extend the config definition to include the additions specified below
1. Run Check
    1. Implement the `section-exists` rule
    1. Loop through checks for the system and run them
    1. Format output to JSON and pretty print to stdout
    1. If one or more checks result in error, return non-0 error code

### Configuration File

```yaml
systems:
  - id: local
    docs: ...
    checks:
      - id: run-locally
        description: Ensure that instructions on how to run the system locally for development exist. 
        rule: section-exists
        options:
          document: README.md
          section: Running Locally
          severity: ERROR
          allowTodos: false
```

### Output
Note that each check run will have an entry in the results array.

```js
{"results": [
  {
    "system": "local",
    "id": "run-locally",
    "description": "Ensure that instructions on how to run the system locally for development exist.",
    "rule" "section-exists",
    "options": {}, // Contains options used when running
    "pass": false,
    "severity": "ERROR", // Will only be present if pass = false
    "message": "The section 'Running Locally' must exist in 'README.md' without TODOs."
  },
  {...}
]}
```

## Estimate
1-3 days

## Plan Endorsement
2025-03-03 @compiledpanda

# Implementation
https://github.com/appgardenstudios/hyaline/pull/12

## Execution Result
https://github.com/appgardenstudios/hyaline/commit/60b5493afdcade796a64e0999cdbf74d6476470e

## Communication
N/A

## Verification Result
The following results were obtained after setting up as detailed below and after running the following commands:

```
$ make build
$ ./hyaline extract current --config ./_example/config.yml --system local --output ./current.db
$ ./hyaline check --config ./_example/config.yml --current ./current.db --system local
```

(Note that current.db was deleted between runs)

### Run Check with allowTodos false
```yaml
checks:
  - id: run-locally
    description: Ensure that instructions on how to run the system locally for development exist. 
    rule: section-exists
    options:
      document: README.md
      section: Running Locally
      severity: ERROR
      allowTodos: false
```

#### Running Locally missing
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/6e3d0c83-45cb-4536-82d2-53243812a7cb" />

#### Running Locally empty
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/30f62df4-c971-4a1d-a59b-b7e3508ac34f" />

#### Running Locally present w/ TODO
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/7d58354b-36ce-4066-bb23-db0e7bda294e" />

#### Running Locally present w/o TODO
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/5ccc43de-3947-4e36-9630-499bb33e3872" />

### Run Check with allowTodos true
```yaml
checks:
  - id: run-locally
    description: Ensure that instructions on how to run the system locally for development exist. 
    rule: section-exists
    options:
      document: README.md
      section: Running Locally
      severity: ERROR
      allowTodos: true
```

#### Running Locally missing
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/3ed25f97-5345-4873-bfef-33a2862016a3" />

#### Running Locally empty
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/d27db7a6-79a6-4e2a-912a-24639b03c418" />

#### Running Locally present w/ TODO
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/1a8bb4b9-f49c-45dc-99bd-7d54a309772b" />

#### Running Locally present w/o TODO
<img width="942" alt="Image" src="https://github.com/user-attachments/assets/9b1c0e20-fb9f-4d94-bab8-e044f0b59bb1" />

# Completion
2025-03-11 @compiledpanda 

# Review
2025-03-12 @compiledpanda 

## Evaluation
The implementation of the rule options was a bit messy, as there wasn't an easy way to type the options block statically when parsing the yaml as each rule implemented its own options. If possible in the MVP the options will be able to be parsed/checked using the standard yaml parser.

The rule implementation was straightforward as well. The only consideration is what to do when there are multiple documentation files with the same file name (i.e. 2 README.md files from 2 separate repos, like app and infra). We probably need to extend the rule to have an optional preference for which documentation set it is looking at.

## Validation
As a developer I was able to run `hyaline check` to check and make sure the extracted documentation contains a section on running the system locally.

## Follow Up
None

# Finished
2025-03-12 @compiledpanda
