### ISSUE TITLE
Open Beta - changes - config refactor

### ISSUE THREAD

**Issue by compiledpanda** [appgardenstudios/hyaline#64]
# Description
Update the configuration schema to make it flow better.

## Source(s)
* Feature: https://github.com/appgardenstudios/hyaline/issues/27.

## Outcome
After this change is complete the configuration schema will be tidy and cohesive.

## Size
Medium.

## Justification
See https://github.com/appgardenstudios/hyaline/issues/27.

# Prioritization
See https://github.com/appgardenstudios/hyaline/issues/27.

# Plan
1. https://github.com/appgardenstudios/hyaline/issues/87
2. https://github.com/appgardenstudios/hyaline/issues/88

### Config layout
```yaml
llm: # configuration for the LLM
  provider: anthropic | testing # The provider
  model: # specific to the provider
  key: # The API key to use

github: # GitHub configuration
  token: # The PAT to use for change extraction

systems:
  - id: # The system ID
    code: # Code Source
      - id: # The ID of the Code Source
        extractor: # Code extractor configuration
          type: fs|git # The type of the extractor
          options: # fs options
            path: # The path to use for extracting
          options: # git options
            repo: # The git repo (ssh or http)
            branch: # The branch to extract from (defaults to main)
            path: # The local path of the repo. If not set an in memory fs will be used
            clone: bool # If true hyaline will clone the repo, if not it will use the repo in place
            auth: # authentication options
              type: http | shh # the type of authentication
              options: # http auth options
                username: # The username to use (defaults to git)
                password: # The password or PAT to use
              options: # ssh auth options
                user: # The ssh user (defaults to git)
                pem: # The pem contents to use
                password: # The password for the pem file (if any)
          include: [glob] # A list of blobs to include. Uses doublestar
          exclude: [glob] # A list of blobs to exclude. Uses doublestar
    documentation: # Documentation Source
      - id: # The ID of the Documentation Source
        type: md|html # The type of documentation
        options: # Documentation source options
          selector: # If set and documentation type is html, this selector is used to extract the documentation from the html. Uses cascadia
        extractor: # Documentation extractor configuration
          type: fs|git|http # The type of the extractor
          options: # fs options
            path: # The path to use for extracting
          options: # git options
            repo: # The git repo (ssh or http)
            branch: # The branch to extract from (defaults to main)
            path: # The local path of the repo. If not set an in memory fs will be used
            clone: bool # If true hyaline will clone the repo, if not it will use the repo in place
            auth: # authentication options
              type: http | shh # the type of authentication
              options: # http auth options
                username: # The username to use (defaults to git)
                password: # The password or PAT to use
              options: # ssh auth options
                user: # The ssh user (defaults to git)
                pem: # The pem contents to use
                password: # The password for the pem file (if any)
          options: # http options
            baseURL: # The base URL to use for pattern matching
            start: # If set, the starting URL. If not set baseURL is used
            headers: # additional headers to set on the http request(s)
              <key>: <value>
          include: [glob] # A list of blobs to include. Uses doublestar
          exclude: [glob] # A list of blobs to exclude. Uses doublestar
        includeDocuments: [] # Array of common document IDs to include
        documents: # Document metadata about our desired state
          - name: # The name (including relative path) of the document
            purpose: # the purpose of the document
            required: bool # True if this document is required
            ignored: bool # True if this document should be ignored when checking
            sections: # The section(s) in this document
              - name: # The name of this section
                purpose: # The purpose of this section
                required: bool # True if this section is required
                ignored: bool # True if this section should be ignored when checking
                sections: [] # The section(s) in this section
                updateIf: ... # Update if certain criteria are met
            updateIf: # Update if certain criteria are met
              touched: # Update if any files matching this glob are touched
                - codeID: # The ID of the code source. If blank glob matches any
                  glob: # glob to match against. Uses doublestar
              inserted: # Update if any files matching this glob are inserted
                - codeID: # The ID of the code source. If blank glob matches any
                  glob: # glob to match against. Uses doublestar
              modified: # Update if any files matching this glob are modified
                - codeID: # The ID of the code source. If blank glob matches any
                  glob: # glob to match against. Uses doublestar
              renamed: # Update if any files matching this glob are renamed
                - codeID: # The ID of the code source. If blank glob matches any
                  glob: # glob to match against. Uses doublestar
              deleted: # Update if any files matching this glob are deleted
                - codeID: # The ID of the code source. If blank glob matches any
                  glob: # glob to match against. Uses doublestar
commonDocuments: # Shared/common documents that can be referenced by documentation sources
  - id: # Desired State ID
    documents: ... # Document metadata
```

## Estimate
See Child Change estimates

## Plan Endorsement
2025-05-09 @compiledpanda 

# Implementation
See child implementation links.

## Execution Result
See child execution results.

## Communication
N/A

## Verification Result
See child verification results.

# Completion
2025-05-13 @compiledpanda 

# Review
2025-05-16 @compiledpanda 

## Evaluation
Fairly smooth. There was a miss on the document/section path/id -> name change that required a follow up ticket, but nothing else of note to report.

## Validation
The configuration schema is updated and flows better now.

## Follow Up
* (none)

# Finished
2025-05-16 @compiledpanda
